### ISSUE TITLE
Confirmation that generated image is compliant with "How to Capture a Linux Virtual Machine to Use as a Template"?

### ISSUE THREAD

**Issue by cyrille-leclerc** [MSOpenTech/packer-azure#64]
Hello,

I am sorry to use the issue tracker for a question but I did not find a forum.

Can you confirm that packer-azure follow the recommendations of [Azure > How to Capture a Linux Virtual Machine to Use as a Template](http://azure.microsoft.com/en-us/documentation/articles/virtual-machines-linux-capture-image/) and thus are aligned with the expectations of the [Certification Test Tool for Azure Certified](http://www.microsoft.com/en-us/download/details.aspx?id=44299) ?

I saw in [driver_restapi/builder.go](https://github.com/MSOpenTech/packer-azure/blob/ae90909ece1ded06ccdb6ea25ccf780f2e76eb91/packer/builder/azure/driver_restapi/builder.go#L326) that `waagent -deprovision` is properly called so I guess it is ok.

Cyrille

**Comment by paulmey** [comment]
From what I read on the first link, I think packer-azure indeed follows that recipe, only using service management API calls instead of mouse and keyboard. 

You may be able to run packer with [-debug](https://packer.io/docs/command-line/build.html#_debug) and some [extra logging](https://packer.io/docs/other/debugging.html). The extra logs will tell you the [location of the private key file](https://github.com/MSOpenTech/packer-azure/blob/master/packer/builder/azure/driver_restapi/targets/lin/step_create_cert.go#L193) and the debug flag will make packer wait after each step. That way you could run the tool just before or after os generalization (I'm not sure when it should run?).

**Comment by cyrille-leclerc** [comment]
Thanks @paulmey I have the same feeling that packer-azure follows that recipe and my Azure image passes the certification tool so things seem to be ok for me.

I'll look more in details at the logs when i'll have time.

Cyrille
