### ISSUE TITLE
Change the default username "packer" 

### ISSUE THREAD

**Issue by fernandoneto** [MSOpenTech/packer-azure#67]
Hi 

i would like to know is it is possible change the default username that packer use to create images in azure. 
everytime i create a image in azure the default user is packer and i want to change it to ubuntu.

best regards
Fernando Neto

**Comment by paulmey** [comment]
I think it would be as easy as making the username property on the [config struct](https://github.com/MSOpenTech/packer-azure/blob/22b26cd1f648f082a2078810a5a72df60330e3f8/packer/builder/azure/driver_restapi/builder.go#L46) public. I'm not sure that you would be able to use a user named ubuntu on ubuntu, because on ubuntu the ubuntu user already exists. Not sure how well that is handled, both by ubuntu and the azure agent, but we can figure that out later... :smile:
