### ISSUE TITLE
Error Removing Temporary Azure Disk

### ISSUE THREAD

**Issue by wallies** [MSOpenTech/packer-azure#83]
Received this error when trying to build image with Ubuntu 14.04 LTS Medium in North Europe.

Error Removing Temporary Azure Disk: Error response from Azure. Code: ConflictError, Message: Windows Azure is currently performing an operation on deployment  that requires exclusive access. Please try again later for operation on disk or image  associated with the deployment

**Comment by paulmey** [comment]
Thanks for reporting this. I've been meaning to open an issue for this. We need to add some retries sound this call (and probably all others). This error happens intermittently and is result of some locks not being cleaned up immediately by Azure. It's kind of sad to have to build again, especially since the provisioning already succeeded...

**Comment by paulmey** [comment]
Fixed by #88
